# Generated by Django 2.2 on 2019-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='asistencia',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
